/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class novamesh_CpuNativeStats */

#ifndef _Included_novamesh_CpuNativeStats
#define _Included_novamesh_CpuNativeStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     novamesh_CpuNativeStats
 * Method:    getCpuNativeStatsJsonNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_novamesh_CpuNativeStats_getCpuNativeStatsJsonNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
