/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class novamesh_MaliGpuStats */

#ifndef _Included_novamesh_MaliGpuStats
#define _Included_novamesh_MaliGpuStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     novamesh_MaliGpuStats
 * Method:    getGpuStatsJsonNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_novamesh_MaliGpuStats_getGpuStatsJsonNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
